apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: appdirect-config
spec:
  groups:
    - name: display_opts
      title: Display Options
      description: Set AppDirect Display Options Below to show
      items:
      - name: ingress_IP
        title: Enter an IP Address to Validate!
        type: text
      - name: page-message-input
        title: Message to Display
        help_text: Enter message to display when browsing to msg page
        type: text
        default: "This is the default message"
      - name: display-hidden
        value: 'repl{{ ConfigOption "hidden-field" }}'
        type: text
      - name: hidden-field
        value: repl{{ RandomString 16 "[a-zA-Z0-9]" }}
        type: text
        when: '{{repl ConfigOptionEquals "ingress_IP" "127.0.0.1"}}'

