apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: postgresql
type: Opaque
data:
  postgres-password: '{{repl ConfigOption "embedded_postgres_password" | Base64Encode}}'
