apiVersion: v1
kind: Service
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "postgres_type" "embedded_postgres"}}'
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql