apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "postgres_type" "embedded_postgres"}}'
spec:
  type: NodePort
  ports:
  - name: postgresql
    port: 5432
    nodePort: 5432
    targetPort: postgresql
  selector:
    app: postgresql