apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: app-slug
spec:
  title: AppDirect
  icon: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/example-nginx
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
