apiVersion: troubleshoot.replicated.com/v1beta1
kind: Analyzer
metadata:
  name: app-direct-analyzer
spec:
  analyzers:
    - textAnalyze:
        checkName: "checkEnvVars"
        fileName: copy-my-file/env_vars.txt
        regex: '*fernando*'
        outcomes:
          - pass:
              message: this is the pass message
          - fail:
              message: this is the fail message