apiVersion: troubleshoot.replicated.com/v1beta1
kind: Analyzer
metadata:
  name: app-direct-analyzer
spec:
  analyzers:
    - textAnalyze:
        checkName: "checkDebug"
        fileName: /app-direct-deployment-*.log
        regex: 'Debug mode: off'
        outcomes:
          - pass:
              message: Debug Mode is Off
          - fail:
              message: Debug Mode is On          